QuantEcon/quantecon-book-theme

quantecon_book_theme/__init__.py, quantecon_book_theme/launch.py, quantecon_book_theme/layout.html
This PR fixes a few issues:
https://github.com/QuantEcon/quantecon-book-theme/issues/16
https://github.com/QuantEcon/quantecon-book-theme/issues/15
https://github.com/QuantEcon/quantecon-book-theme/issues/14
will close these issues once tested on netlify.
=> 👌IMPROVE: Style and Functionality improvements

quantecon_book_theme/layout.html
Updates hover text for sidebar
=> [MAINT] update text for hover message

setup.py
I reckon we should increase the version as `sphinx-book-theme` has done it as well. https://github.com/executablebooks/sphinx-book-theme/blob/master/setup.py 😬 
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/33
=> ♻️ REFACTOR: Increasing dependency versions as in sphinx-book-theme

quantecon_book_theme/layout.html, quantecon_book_theme/scss/_syntax.scss, quantecon_book_theme/scss/quantecon-book-theme.scss
=> Theme styling update and fixes

quantecon_book_theme/__init__.py
fix for this failing run :https://github.com/QuantEcon/lecture-python.myst/runs/1329341173
=> 🐛 BUG: Checking github_repo in srcdir

quantecon_book_theme/layout.html, quantecon_book_theme/scss/quantecon-book-theme.scss
=> Add Creative Commons license page footer

quantecon_book_theme/scss/quantecon-book-theme.scss
Feature similar to  https://github.com/executablebooks/sphinx-book-theme/pull/250
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/66
@mmcky I reckon we don't need to mention it in the docs here, as it is gonna be mentioned in `jb`
=> 👌 NEW: Added style for scroll output tag

quantecon_book_theme/scss/quantecon-book-theme.scss
With this PR,
```
```{code-cell} python3
---
tags: [scroll-input]
---
```
will work the same for input cells, as `scroll-output` was working for output cells.
=> 👌 NEW: Tag for scroll input

.github/workflows/ci.yml, quantecon_book_theme/layout.html
Notebooks will currently be fetched from `_notebooks` but could be updated to be served from a repository later on.
=> MAINT: add download notebook link to be served from _notebooks folder

quantecon_book_theme/scss/quantecon-book-theme.scss
Centre aligns img elements in output cells.
=> Centered figures

quantecon_book_theme/scss/quantecon-book-theme.scss, quantecon_book_theme/static/scripts.js
This PR make small adjustments to the table styling (#79).
- Match styling of sphinx site
- Remove margin from paragraph elements within cells
- Restore JS wrapping of tables with div for horizontal scrolling on mobile
=> Table styling

tests/test_build/test_build_book.html
Regression file had a class missing.
=> 🐛 FIX: Fixing a test fixture

quantecon_book_theme/__init__.py
Reverts QuantEcon/quantecon-book-theme#112
=> Revert "🚀 RELEASE: v0.1.6b"

.github/workflows/ci.yml
Just a maintenance PR to fix `CI`
=> TEST: Enable branch for building a test case

quantecon_book_theme/__init__.py
Sets up for new release `v0.4.1`
=> RELEASE: setup v0.4.1

quantecon_book_theme/layout.html, quantecon_book_theme/static/quantecon-book-theme.282f51e609929a8ffbc5260c6713b9cc.js, quantecon_book_theme/theme.conf, src/jinja/theme.conf.j2, src/js/quantecon-book-theme.js
fix it in the next release, and fix this issue https://github.com/QuantEcon/quantecon-book-theme/issues/207
=>  Removing search hint for now.

quantecon_book_theme/__init__.py
This PR sets up a release for `0.5.1`
=> RELEASE: v0.5.1

src/quantecon_book_theme/__init__.py
This release adds in the upgraded text colours to improve the dark theme.
=> RELEASE: v0.7.1

src/quantecon_book_theme/__init__.py
This PR prepares for the release of v0.7.2
=> update version for v0.7.2

src/quantecon_book_theme/assets/styles/index.scss
This is a minor fix to touch up the pre-commit in #265
=> FIX: minor fix for pre-commit

src/quantecon_book_theme/__init__.py
This PR updates the logo location using `logo_url`
=> FIX: update new logo location for jb>=1.0

src/quantecon_book_theme/__init__.py, src/quantecon_book_theme/assets/scripts/index.js, src/quantecon_book_theme/launch.py, src/quantecon_book_theme/theme/quantecon_book_theme/layout.html
This PR adjusts jupyterhub links for connecting to local Jupyter Hub instances
=> FIX: adjust jupyterhub links

src/quantecon_book_theme/__init__.py
=> RLS: setup for v0.9.1

src/quantecon_book_theme/assets/scripts/index.js
@mmcky Please review the changes.
=> Update index.js to fix reference error

src/quantecon_book_theme/__init__.py
Sets up for release of `v0.9.3`
=> RLS: setup for v0.9.3
