quantecon_book_theme/layout.html
The `view source` and `download ipynb` links were opening the asset instead of downloading them in **netlify**. This PR tries to fix that.
=> 🐛 BUG: download links

quantecon_book_theme/scss/quantecon-book-theme.scss
This PR at present fixes CSS styling for labels in math equations
closes https://github.com/QuantEcon/quantecon-book-theme/issues/12
=> 🐛 FIX: CSS styling

quantecon_book_theme/layout.html, tests/test_build/test_build_book.html
Thanks @DrDrij for the solution. This PR makes the header icons available in local previews.
TODO: 
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/10
=> 🐛 BUG: header buttons were missing in local previews

docs/configure.md, quantecon_book_theme/__init__.py, quantecon_book_theme/layout.html, quantecon_book_theme/theme.conf
We can now add extra features in the documentation website or modify an existing one, using plugins in javascript files.
config option is:
```
html_theme_options = {
"plugins_list": ["path-relative-to-config-file.js"]
}
```
or in jb:
```
sphinx:
plugins_list: ['path-relative-to-config-file.js']
```
The background implementation is basically copying all the js files specified in `plugins_list` to a new `plugins` directory in outdir of the build. And including script tags pointing to these js files in the base HTML file of the website.
=> ✨ NEW: Add config support to specify javascript plugins

.github/workflows/ci.yml, quantecon_book_theme/layout.html, quantecon_book_theme/scss/quantecon-book-theme.scss, tests/test_build/test_build_book.html
Discussed changes to toolbar and sidebar.
I am not sure where the `qe-menubar.js` script is being added along the line but this can now be removed.
The PR should adjust the theme as so:
=> Add QE logo to toolbar,  rearrange icons, fixed sidebar

quantecon_book_theme/layout.html, tests/test_build/test_build_book.html
To read google_analytics_id variable, we need to prepend it with `theme_`, as all variables in `html_theme_options` of sphinx get prepended with that automatically by sphinx.
=> 🐛 BUG: google analytics_id in layout

codecov.yml
This sets codecov at `60%` and will raise an issue to make coverage improvements when becomes a priority
=> adjust codecov for now and open issue to improve

quantecon_book_theme/layout.html, tests/test_build/escaped_description.html
This PR adds the same metadata present in the current lecture site to the theme layout file.
The required metadata variables have been added to the source repo:
https://github.com/QuantEcon/lecture-python-programming.myst/pull/67
=> HTML metadata

quantecon_book_theme/__init__.py
This PR adjust to use rfind as github action runners lists the repo twice in path.
=> FIX: View Source when building on Github Actions

quantecon_book_theme/scss/quantecon-book-theme.scss
Added styling of `highlight` class for code-cells in the theme, in accordance with the discussion in this PR https://github.com/executablebooks/MyST-NB/pull/269 . 
This current PR basically removes the background styling of the `highlight` cell so that styles migrated from other packages like pygments do not affect it.
=> 👌 IMPROVE: Background style for code cells

quantecon_book_theme/scss/_syntax.scss, quantecon_book_theme/scss/quantecon-book-theme.scss
At present we are commenting out the remnants of `Out` text for code-cells. 
Created a feature request for it with the ability to show execution count in code-cells. https://github.com/QuantEcon/quantecon-book-theme/issues/83
fixes https://github.com/QuantEcon/lecture-python.myst/issues/40
=> 🐛 FIX: Code-block 'Out' text

quantecon_book_theme/scss/quantecon-book-theme.scss
Adds an align center style to all `figure` elements. Adding `align-left` or `align-right` will override default behaviour.
=> Add align center to figure class #80

.pre-commit-config.yaml, setup.py, tests/test_build/test_build_book.html
In pre-commit-config.yaml, the rev of black is `stable` :
```
- repo: https://github.com/psf/black
rev: stable
hooks:
- id: black
```
which is throwing the following error:
have changed the rev to the latest version:
```
- repo: https://github.com/psf/black
rev: 20.8b1
hooks:
- id: black
```
=> 🐛 FIX: fixing black version to prevent pre-commit failure

quantecon_book_theme/scss/quantecon-book-theme.scss, quantecon_book_theme/static/scripts.js
This PR changes the MathJax font size setting. Rather than using CSS we now set relative size (92%) using JS in the MathJax config. This is to hopefully fix the Safari rendering issue, where the element size was smaller than the rendered equation - causing overlaps (https://github.com/QuantEcon/lecture-python.myst/issues/117).
=> FIX: Inline math collide

quantecon_book_theme/__init__.py, quantecon_book_theme/layout.html, setup.py, tests/test_build/test_build_book.html
Mostly adapting `generate_nav_html ` function, which has changed in `pydata-sphinx-theme~=0.6.0`. SInce, this version is now pinned by `jb`, it should be adapted in `quantecon-book-theme` .
=> ♻️ REFACTOR: Pydata-sphinx-theme~=0.6.0 adaption

quantecon_book_theme/layout.html
RIght navbar went missing with the `quantecon-book-theme` 0.1.6 release, this PR fixes it. 
The default navbar HTML inherited from `pydata-sphinx-theme` also has numbering of the sections included. (when numbered:true)
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/110
=> 🐛 FIX: Right side navbar fix

quantecon_book_theme/layout.html
The below dropdown is shown only if book pdf is accessible 
else clicking on the icon, directly goes to downloading lecture pdf.
=> 👌 IMPROVE: Showing download dropdown when book pdf is present 

quantecon_book_theme/layout.html
The google analytics code feature is re-added to the layout.
The config variable to specify google analytics is the same as before:
```
html: 
google_analytics_id: <analytics id>
```
or
```
sphinx:
config:
google_analytics_id: <analytics id>
```
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/134
=> 🐛 FIX: Adding google analytics id

quantecon_book_theme/layout.html, quantecon_book_theme/static/quantecon-book-theme.f77f720613e25edc6a92ce4459c6ecdc.js, src/js/quantecon-book-theme.js
Added hardcoded mathjax inline script, before mathjax itself loads, to make the config work, according to: http://docs.mathjax.org/en/latest/web/configuration.html#configuration-using-an-in-line-script
The present config option to configure mathjax in `_config.yml` wont work with mathjaxv3 as mentioned in the following comment. https://github.com/executablebooks/jupyter-book/blob/master/docs/_config.yml#L66
Once, we start using sphinx v4, we can use `mathjax3_config` to set all the macros in the configuration file https://sphinx--9094.org.readthedocs.build/en/9094/usage/extensions/math.html#confval-mathjax3_config .
But, for now, we will have to make with hardcoded configuration in the theme.  
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/135
=> 🐛 FIX: Configuring mathjax before the script that loads mathjax

quantecon_book_theme/__init__.py, quantecon_book_theme/layout.html
Decoding mathjax version based on `mathjax_path` config variable, and using the hardcoded mathjax configuration only for version 3. Which will be removed at a later stage https://github.com/QuantEcon/quantecon-book-theme/issues/138
=> 👌 IMPROVE: Checking mathjax version and functioning accordingly

quantecon_book_theme/__init__.py, quantecon_book_theme/layout.html
Show download notebook links only if `_notebooks` folder is present in HTML output directory.
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/156
=> 👌 IMPROVE: Conditional links for download notebooks

docs/launch.md, quantecon_book_theme/launch.py
It was using the variable `repository_branch ` earlier, which was a mistake. As `repository_branch ` is meant to hold the value of the source file repository branch name.
=> 🐛 FIX: Using `nb_branch` for launch button url links

quantecon_book_theme/__init__.py
The default branch is 'main'.
If any other branch is required then we need to set the option
```
nb_branch: <branch_name>
```
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/202
=> FIX: 'View source' link

src/quantecon_book_theme/assets/styles/index.scss
fixes #227 
The screenshot of fixes are (ordering based on issue #227 ):
1) 
2) 
3)  I feel the images look better this way in dark mode. If the background is white, its too bright and defeats the purpose of dark-theme. What do you think @mmcky @HumphreyYang 
4) 
5) 
cc: @HumphreyYang  @mmcky
=> FIX: Dark theme styling fixes

.github/workflows/tests.yml, docs/configure.md, src/quantecon_book_theme/assets/scripts/index.js, src/quantecon_book_theme/assets/styles/index.scss, src/quantecon_book_theme/theme/quantecon_book_theme/layout.html, src/quantecon_book_theme/theme/quantecon_book_theme/theme.conf, tests/sites/base/conf.py
This PR adds the ability to specify a dark-mode version of your logo. 
To use a separate logo image for dark mode, simply set it in configuration using the following setting:
```
dark_logo: logo-image-dark-mode
```
The image is expected to be in the `_static` folder of your source repository
=> ENH: Adding logo image for dark mode

docs/layout.md, src/quantecon_book_theme/__init__.py, src/quantecon_book_theme/assets/scripts/index.js, src/quantecon_book_theme/assets/styles/_margin.scss, src/quantecon_book_theme/assets/styles/index.scss
Desktop :  
Mobile:
TODO:
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/229
=> Styling margin directive from sphinx-book-theme

docs/configure.md, src/quantecon_book_theme/assets/scripts/index.js, src/quantecon_book_theme/assets/styles/index.scss, src/quantecon_book_theme/theme/quantecon_book_theme/layout.html, src/quantecon_book_theme/theme/quantecon_book_theme/theme.conf
Author names from the description need to be removed from individual repos. 
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/233
=> Adding author names in title of the main page

src/quantecon_book_theme/assets/styles/index.scss
This PR introduces the following colour: 
Please refer to the issue https://github.com/QuantEcon/quantecon-book-theme/issues/235
fixes https://github.com/QuantEcon/quantecon-book-theme/issues/235
=> [Dark Theme] Text Colours for Titles and SideBar

src/quantecon_book_theme/assets/styles/index.scss
By changing the way we address the admonition title, we allow the sphinx proof stylesheet to affect background colour when using QuantEcon book theme.
Addressing: https://github.com/QuantEcon/lecture-python-intro/pull/493
=> Adjust admonition title background specificity to allow proof override

.github/workflows/ci.yml, .github/workflows/tests.yml, pyproject.toml, src/quantecon_book_theme/__init__.py, src/quantecon_book_theme/assets/styles/index.scss, src/quantecon_book_theme/launch.py, tests/sites/base/conf.py, tests/test_build/test_build_book.html, tox.ini
=> MAINT: pre-commit fix and master->main

pyproject.toml, src/quantecon_book_theme/__init__.py
=> MAINT: update libsass and docutils pins

src/quantecon_book_theme/theme/quantecon_book_theme/layout.html
This PR updates the functionality for `View Source` button to link to the hosting repo rather than the full path to the repo + document. `QuantEcon` has decided this would be more robust and useful (see https://github.com/QuantEcon/meta/issues/133)
=> ENH: enable links to github repo rather than document for view source

.pre-commit-config.yaml, docs/configure.md, src/quantecon_book_theme/theme/quantecon_book_theme/layout.html, src/quantecon_book_theme/theme/quantecon_book_theme/theme.conf
This PR
- enables configuration to remove the QuantEcon logo from the titlebar
- adds in footer text to indicate the theme was made by QuantEcon
- updates some theme colours when `quantecon_project = False`
```python
html_theme_options = {
...
"quantecon_project": False,
...
}
```
and if using `Jupyter-book`
```yaml
sphinx:
config:
quantecon_project: False
```
=> ENH: Optional QuantEcon logo in titlebar with Theme Adjustments

src/quantecon_book_theme/__init__.py
=> RLS: prepare for v0.8.0
